apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
spec:
  replicas: {{ .Values.keycloak.replicas }}
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.image.pullPolicy }}
          args:
            - start-dev
          env:
            - name: TZ
              value: {{ .Values.keycloak.env.TZ | quote }}
            - name: KC_DB
              value: {{ .Values.keycloak.env.KC_DB | quote }}
            - name: KC_DB_URL
              value: {{ .Values.keycloak.env.KC_DB_URL | quote }}
            - name: KC_DB_USERNAME
              value: {{ .Values.keycloak.env.KC_DB_USERNAME | quote }}
            - name: KC_DB_PASSWORD
              value: {{ .Values.keycloak.env.KC_DB_PASSWORD | quote }}
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.env.KEYCLOAK_ADMIN | quote }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.keycloak.env.KEYCLOAK_ADMIN_PASSWORD | quote }}
            - name: KC_HOSTNAME
              value: {{ .Values.keycloak.env.KC_HOSTNAME | quote }}
          ports:
            - containerPort: 8080
          resources:
{{ toYaml .Values.keycloak.resources | indent 12 }}