apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: keycloak
spec:
  selector:
    app: postgres
  ports:
    - port: {{ .Values.service.postgresNodeport.port }}
      targetPort: {{ .Values.service.postgresNodeport.targetPort }}
      nodePort: {{ .Values.service.postgresNodeport.nodePort }}
  type: {{ .Values.service.postgresNodeport.type }}