apiVersion: v1
kind: Service
metadata:
  name: searxng
  namespace: search
spec:
  selector:
    app: searxng
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}