{{- if .Values.ingress.adm.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trend-adm
  namespace: trend
spec:
  ingressClassName: {{ .Values.ingress.adm.ingressClassName }}
  rules:
  {{- range .Values.ingress.adm.hosts }}
    - host: {{ .host }}
      http:
        paths:
  {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .backend.service.name }}
                port:
                  number: {{ .backend.service.port.number }}
  {{- end }}
  {{- end }}
{{- end }}