apiVersion: v2
name: trend-app
description: A Helm chart for trend-app
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: searxng
    version: 0.1.0
    repository: file://./charts/searxng
  - name: keycloak
    version: 0.1.0
    repository: file://./charts/keycloak
  - name: trend
    version: 0.1.0
    repository: file://./charts/trend